### ISSUE TITLE
Server start fails with Opel on /vehicles

### ISSUE THREAD

**Issue by andig** [flobz/psa_car_controller#32]
**Describe the bug**

```
2021-02-24 16:40:07,064 :: INFO :: server start
Traceback (most recent call last):
  File "/Users/andig/htdocs/psa_car_controller/server.py", line 59, in <module>
    logger.info(web.app.myp.get_vehicles())
  File "/Users/andig/htdocs/psa_car_controller/MyPSACC.py", line 210, in get_vehicles
    for vehicle in res.embedded.vehicles:
AttributeError: 'NoneType' object has no attribute 'embedded'
2021-02-24 16:40:09,290 :: INFO :: save config change
```

**To Reproduce**
Start server with opel config

**Config file**

    {
        "client_id": "xx",
        "client_secret": "xx",
        "customer_id": "",
        "proxies": {
            "http": "",
            "https": ""
        },
        "realm": "clientsB2COpel",
        "refresh_token": "xx",
        "remote_refresh_token": "",
        "weather_api": null
    }

**Environment (please complete the following information):**
 - OS: OSX

**Additional context**
Looking at the requests, the `/vehicles` cannot be retrieved:

    HTTP/1.1 401 Unauthorized
    Connection: close
    Content-Type: application/json
    Set-Cookie: PSACountry=DE;Domain=.groupe-psa.com;Path=/
    Vary: Accept-Encoding
    Www-Authenticate: default
    X-Backside-Transport: FAIL FAIL

    { "httpCode":"401", "httpMessage":"Unauthorized", "moreInformation":"Not registered to plan" }

**Comment by flobz** [comment]
Are all function of your myopel working properly ?

**Comment by andig** [comment]
Argh. Seems user has no OpelConnect. Sorry for the noise :/

**Comment by alexan-d** [comment]
hello i support andig with the test, according to opel all networked services are successfully subscribed? what about the info "not registered to plan", could it be because of that? The free plan of the api "Connected Car API (1.0.0)" is currently subscribed to in the dummy app for the clientid. Are other or different plans required?

**Comment by flobz** [comment]
> The free plan of the api "Connected Car API (1.0.0)" is currently subscribed to in the dummy app for the clientid.

Where did you find those information?
Can you confirm that changing the charging hour works on the android apps? 
Can you give me a part of the client id and client secret?

**Comment by andig** [comment]
@flobs can we share credentials using Signal?

**Comment by alexan-d** [comment]
@flobz 
the subscribed apis are displayed on the psa developer website/user account next to the app, see attachment.
i have just tested the delayed loading in the myopel app, it works. which part of the clientid and the client secret are required?
![app+subscription](https://user-images.githubusercontent.com/78390346/109169407-106c8a00-7780-11eb-9e5c-3e44095e23e5.jpg)

**Comment by flobz** [comment]
Are you using the client id/client secret from developer website?

**Comment by flobz** [comment]
I take time to write a file called README.md if you don't read it what is the point?
In this file (if you had read it) it says that client id and client secret are taken from Android app not psa developers web site.

**Comment by andig** [comment]
@flobz that's really not best practice :(. But mistakes happen, we're all only human. Thanks a lot for uncovering the root cause, much appreciated!

**Comment by alexan-d** [comment]
**@ flobz** I'm sorry, of course I've read your read.me before i start. I also really respect and appreciate the work you do in it! I'm just not that experienced in programming, so I didn't understand the complex contexts immediately. 

The credentials aren't also (anymore) the problem. I just don't get any sms with the required pincode! 
I have already deleted the otp.bin and retried several times, but I always get stuck at the point where I would have to enter the received code, which is exactly what I don't have. 
My mobile number is stored correctly in the myopel app on my mobile phone, and if I change something there, I also receive an SMS. I'm going crazy.
How is the sms sent by your prog? Could it be because I live in Germany and there is a problem with the country code?

Could you please help me again, I would be very grateful.
