### ISSUE TITLE
Feature request: Load Email/password from --config file in addition to cli and promte

### ISSUE THREAD

**Issue by vlycop** [flobz/psa_car_controller#44]
**Additional context**
As a "safety" measure, it would be nice to not have that data in clear when doing a ps for exemple.
The config file can be 0600 and limited to a system user, making it "safer"

**Comment by flobz** [comment]
Hello,
What do you think about environment variable ?
You can create a litle script to define USER_EMAIL and USER_PASSWORD envrionement variable and then start the app.
I add this in 72ad86795889e01cf8548e3df03d16ac46a3d817. This isn't in a master branch because it need to be more tested.

**Comment by vlycop** [comment]
Thank you for this addition
Having the choice of environment variable is a good thing ! but sadly not that much secure :(
for example you can find in the mysql doc : https://dev.mysql.com/doc/refman/8.0/en/environment-variables.html

```
Use of MYSQL_PWD to specify a MySQL password must be considered extremely insecure and should not be used. Some versions of ps include an option to display the environment of running processes. On some systems, if you set MYSQL_PWD, your password is exposed to any other user who runs ps. Even on systems without such a version of ps, it is unwise to assume that there are no other methods by which users can examine process environments. 
```

I have no idea what could it break to add those field in the config file. That's just the first idea that came to me :)
Env is better than argument for sure ! If adding them in the config file is to complicated maybe don't bother with it.

**Comment by jlayec** [comment]
Maybe we can imagine a specific secret.json file?

**Comment by flobz** [comment]
@vlycop I think that both solutions have their advantages and disadvantages. Please look at this : https://stackoverflow.com/questions/12461484/is-it-secure-to-store-passwords-as-environment-variables-rather-than-as-plain-t

Also, the best solution is to never store passwords. I can't be totally sure but normally you don't need the password if your server doesn't stay down too long. 
In fact it should works like the android app, if you don't use it for a while you need to reconnect because the session expire.
That's why I think we should not store password.
In the future if we notice that we need to reconnect sometimes, we can add a config file.

**Comment by flobz** [comment]
I close the issue. Feel free to reopen it if the app ask your password to often.
