### ISSUE TITLE
Internal Ip of Home Assistant is not static

### ISSUE THREAD

**Issue by Gabriele-tomai00** [flobz/psa_car_controller#476]
I integrated Psa Car Controller as addons on HA OS and I find the correct Ip, in my case: 172.30.33.5, but is not static!
Yesterday I couldn't find car info, so I tried by ssh terminal the command "curl -s ip..." and it doesn't work.
I tried another ip address and I found the (differnet) ip: 172.30.33.6.
There is a way to solve it?

Thanks

**Comment by dreimer1986** [comment]
![image](https://user-images.githubusercontent.com/29841368/214913370-305e6e1e-e0ff-4f91-bd54-db3067960944.png)

**Comment by Gabriele-tomai00** [comment]
Thanks.
Are there any contraindications? Is it safe?

**Comment by dreimer1986** [comment]
This is how Docker works. You want it to show up out of it's container, then add a forwarding. It's as safe as the code used is.

**Comment by ennoToUpper** [comment]
I know this answer is pretty late but I figured it might help someone.

In the router you often have names for the servers like homeassistant or localcloud.
These names often can be used instead of an IP and route to that device even if its IP changes.
Sometimes you need to add .local after the name.
As you are using HA often it can be accessed as homeassistant or homeassistant.local.
If you do have access to the router it's probably useful to set the IP as static in the router.

Heres an example:
Instead of 192.16.16.2:5000 use datacenter:5000 or datacenter.local:5000
