### ISSUE TITLE
[Question] what is the rate limit

### ISSUE THREAD

**Issue by hutje** [flobz/psa_car_controller#489]
I can't find any information of the maximum API requests.
What is the limit of request each hour/day?
Would like to know if it is possible (and useful) to do a request every second(?) to monitor the battery etc.

**Comment by sircuri** [comment]
According to the error messages found in the decompiled code of the Peugeot.apk application, there is a limit in the amount of requests that can be made. The exact limit is unclear to me. But I came across error messages that would indicate that you can  exceed the amount of requests made in 30 days. I can't seem to find how long you can get locked out because of it.

But what you want is not possible at all. You're car will not be "awake" all the time. You have to wake up the car and that by itself takes already a few seconds. The wake up procedure is also throttled. Something around 6 times a day. You will get locked out if you keep hammering this API. Your car is a car.. not an IoT device.

I don't really understand why you would want to query for your battery status every second?
