### ISSUE TITLE
Still Invalid value for `type` (Acquire) after update

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#532]
**Describe the bug**

**To Reproduce**
1. what command did you use - tried to get car status
2. when the bug append ? - Since ~10.04.2023? 
3. Does it persist after restarting the program? - yes
4. Does it persist after recreate config by going to http://server_address:port/config? - yes

**Environment (please complete the following information):**
 - OS: Linux
 - Brand and model of car - Corsa
 - Application version (commit number, branch or tag) - fresh update 3.0.12
 - Log from http://server_address:port/log and browser console log - ValueError: Invalid value for `type` (Acquire), must be one of ['Estimated', 'Acquired', 'Estimate', 'Aquire']

**Additional context**
First i stopped the service. 
Then I installed the latest update with  wget https://github.com/flobz/psa_car_controller/archive/refs/heads/master.zip and unzip master.zip

But i still get this error. I also restarted my linux machine. Still the same. I entered logondata again and requested the OTP again.

**Comment by Philippehaz** [comment]
I am also getting this error since I have restarted the server. I am not sure if it is linked to the server restart or something that has changed in PSA API? 
This happens when get_vehicleinfo is called, log extract below:

  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/api_client.py", line 626, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 61, in __init__
    self.type = type
  File "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py", line 131, in type
    raise ValueError(
ValueError: Invalid value for `type` (Acquire), must be one of ['Estimated', 'Acquired', 'Estimate', 'Aquire']
2023-04-15 07:54:04,131 :: INFO :: 192.168.50.2 - - [15/Apr/2023 07:54:04] "GET /get_vehicleinfo/XXX?from_cache=1 HTTP/1.1" 500 -

**Comment by mdkeil** [comment]
You have to use release 3.0.12. | see [commit](https://github.com/flobz/psa_car_controller/commit/619cefd4dc516a9dc3ec2ea0bb339c345a83033e)

**Comment by CWfFO** [comment]
Hi, see my comment. I am already on 3.0.12

**Comment by mdkeil** [comment]
then look at you local "/usr/local/lib/python3.9/dist-packages/psa_car_controller/psa/connected_car_api/models/position_properties.py" at line 129; this must be 

`allowed_values = ["Estimated", "Acquired", "Estimate", "Acquire"]`

**Comment by CWfFO** [comment]
That was the problem. Thanks a lot!!!!
Do i use the wrong commands for an update or how can i avoid this in future?

**Comment by Philippehaz** [comment]
Updated to v3.0.12 and problem fixed for me. Thanks
