### ISSUE TITLE
SMS and PIN after every restart

### ISSUE THREAD

**Issue by CWfFO** [flobz/psa_car_controller#63]
Hi
i am using since today the up2date Version. After every restart i have now to enter a new SMS code and my PIN. Is there any way to avoid this?

1. what command did you use: python3 server.py -f test.json -c charge_config.json -r -l 192.168.99.13  
2. when the bug append ? after every testart
3. Does it persist after restarting the program? yes

    OS: Raspian
    Android app Version [e.g. 26.0] 1.27.1
    Brand and model of car: Opel
    Application version (commit number, branch): master

KR
Christian

**Comment by flobz** [comment]
Hi,
This isn't normal, delete otp.bin and retry.

**Comment by CWfFO** [comment]
No sorry. Still the same behavior

**Comment by flobz** [comment]
Do you have any error in the log?

**Comment by schombat** [comment]
Hi all, 
same behavior here. Since the last update on the application keeps asking for SMS code and PIN. Used to work on Mar 28th. I suppose problem is somehow related to "Merge pull request" #55.  
My first thought was that the problem could be caused by a temporary block of my account (e.g. rate limit exceeded) after I did several retries of starting the server to fix Bug #59 `cannot start server - Opel Corsa-e` by myself before the fix was published, but the problem still persists after >48 hours. 

Command:  `python3 server.py -f test.json -c charge_config1.json -d 9`
OS: BOTH Mac OS w/ Python 3.9.2 AND Raspian w/ Python 3.7.3
Android app version: BOTH MyOPEL 1.29.0 AND MyOPEL 1.28.2
Application version: `master`
Brand and model of car: Opel Corsa-e (without onboard navigation system)

Tried deleting otp.bin, cars.json, charge_config1.json and test.json and new app_decoder runs, but problem persists.

Log shows error `2021-04-02 20:54:30,577 :: ERROR :: remote_refresh_token isn't defined`

Problem seems to be related to the Finalize Action `ActionFinalize` which returns an `<err>NOK:FORBIDDEN</err>`.
`ActionSetup`right before that returns `<err>OK</err>`

mitmproxy shows the following flows:

```
https://idpcvs.opel.com/am/oauth2/access_token	POST	400	167b	135ms
https://idpcvs.opel.com/am/oauth2/access_token	POST	200	973b	173ms
https://api.groupe-psa.com/connectedcar/v4/user/vehicles?client_id=01234567-12ab-1234-1234-1a012ab1a12a	GET	200	2.6kb	514ms
https://idpcvs.opel.com/am/oauth2/access_token	POST	200	956b	175ms
https://api.groupe-psa.com/applications/cvs/v4/mobile/smsCode?client_id=01234567-12ab-1234-1234-1a012ab1a12a	POST	202	31b	631ms
https://otp.mpsa.com/iwws/MAC?action=ActionSetup&mode=activate&id=&lastsync=0&version=Generator-1.0%2F0.2.11&macid=[...]&code=[SMS]	GET	200	754b	139ms
https://otp.mpsa.com/iwws/MAC?action=ActionFinalize&mode=activate&id=&lastsync=0&version=Generator-1.0%2F0.2.11&lang=fr&ack=&macid=macid=[...]&serial=[...]&code=[SMS]&Kma=[...]&pin=[...]&name=Android+SDK+built+for+x86_64+%2F+UNKNOWN&R0=[...]&R1=[...]&R2=[...]	`GET`	200	182b	149ms
https://api.groupe-psa.com/connectedcar/v4/virtualkey/remoteaccess/token?client_id=01234567-12ab-1234-1234-1a012ab1a12a	POST	400	125b	218ms
https://otp.mpsa.com/iwws/MAC?action=ActionSetup&mode=otp&id=&lastsync=0&version=Generator-1.0%2F0.2.11&macid=[...]	GET	200	94b	59ms
```

Step 
`https://otp.mpsa.com/iwws/MAC?action=ActionSetup&mode=activate&id=&lastsync=0&version=Generator-1.0%2F0.2.11&macid=[...]&code=[SMS]`
returns `OK`:
```
<?xml version="1.0" encoding="Iso-8859-1"?>
<ActionSetup>
  <Kiw>285ca6f146c0d6d0ca4f6a219c68b34cac7645958d97f2e99fd0622a8c6f163cdfd05dfe9f01c973d64d2c67dcf90e89906a84d6171ef1d957a238f46260a23c2bd9a36afe4dde1422270ac5ca3d6315bc95ead2eb55fed89e952e55a0b361fe84dd895e593cfa2ae77bf4e75fc4bdb20c8225f06a874dca581948d7a3cac04e200a3b09eb53c012a31d4b63b181dd032c5b3acbcaac816eaddd85953f23e62ba7c4a5382246ac3acc17cb75f9dccfee59addab779654f263f6ce3c40631d973acb1300bd7834ce4927396c21cf3e238dad037c8a4b883e815f422b8eee746b7e38725eee08671dab1021319a43e585826dc6ba29b2c4ff270afce9cf235ff22474b48dafac7dfd272ac5b1fb5ef8ede50f8255e90173e0a06712db235342616cf54b50a33f858cc7970a4047e7e15a54a82eba49ed42f667f8493e35b85261a72ae186d1604090ee24ab9467860a41bf37044bf242c027064805f0b09ea1ab4c4885f775b5a5fe20b4d73f1e7173d3078a5ccc92c82b426bb7da2eb78fe515f</Kiw>
  <Kfact>9f13ba238fbabba08e85d93638e98ef5e48682a9d3e5bc325c3dd6fac8199a6ce09e9b4f373aa6a75a905c3d690f6e3335d1e8e5b748ecec3020a794149033f6ada6896db6d73b8d43b8365bbe15b9ac66f49d4e684a3628f1e9f3deda0c4e24aba771946e6085b92c5ad312477152acf8db01e6aea4b409d5ac1a05c2fd4e95</Kfact>
  <pinmode>1</pinmode>
  <newversion>2.0.0</newversion>
  <newversionurl>http://m.inwebo.com/</newversionurl>
  <err>OK</err>
</ActionSetup>
```

But step 
`https://otp.mpsa.com/iwws/MAC?action=ActionFinalize&mode=activate&...`
returns `<err>NOK:FORBIDDEN</err>`:
```
<?xml version="1.0" encoding="Iso-8859-1"?>
<ActionFinalize>
  <newversion>2.0.0</newversion>
  <newversionurl>http://m.inwebo.com/</newversionurl>
  <err>NOK:FORBIDDEN</err>
</ActionFinalize>
```

and subsequently step
`https://otp.mpsa.com/iwws/MAC&action=ActionSetup&mode=otp&id=&lastsync=0&version=Generator-1.0%2F0.2.11&macid=[...]`
returns `<err>NOK:NODEVICE</err>`

```
<?xml version="1.0" encoding="Iso-8859-1"?>
<ActionSetup>
  <err>NOK:NODEVICE</err>
</ActionSetup>

```

**Comment by flobz** [comment]
Ok, on a fresh myopel install on a smartphone, connect and test remote control.
It should say that you need to reset your account or something like that.

**Comment by CWfFO** [comment]
Hi,
my account isn't blocked. 
Here is a error which i see :
2021-04-03 08:45:26,234 :: ERROR :: remote_refresh_token isn't defined
What is the code you just received by SMS ?

**Comment by flobz** [comment]
Have you followed my instructions?

**Comment by schombat** [comment]
> Ok, on a fresh myopel install on a smartphone, connect and test remote control.
> It should say that you need to reset your account or something like that.

Thanks for the quick response!
I followed your instructions (fresh app install), and the app actually asked for a reset of the app PIN. After doing so, the registration worked again - thanks for the hint.
But: the reported behavior (SMS code and PIN requested after every restart) is still present. 
Log shows error `2021-04-03 10:03:29,207 :: ERROR :: remote_refresh_token isn't defined`, then SMS/PIN are requested. 
But after that another error is logged: `2021-04-03 10:03:59,580 :: ERROR :: can't refresh_remote_token: {'error': 'invalid_grant', 'error_description': 'grant is invalid'}`

**Comment by dreimer1986** [comment]
I had a similar one in the past. I have zero clue if things are still behaving that way, but... rename test.json to config.json and modify the command line accordingly.

**Comment by xammmue** [comment]
I had the same issue after pulling, ommitting `-f test.json` from the command helped.

Problem occurrs as the defined config name from the command is only used for loading but not for saving. PR #64 should fix that behavior

**Comment by CWfFO** [comment]
I changed to the newest files and now i am in a loop:
2021-04-04 10:33:22,610 :: ERROR :: Error during activation: {'newversion': '2.0.0', 'newversionurl': 'http://m.inwebo.com/', 'err': 'NOK:FORBIDDEN'}
And then it sends a new SMS and then the same error again. 
After this i get:
otp.Otp.ConfigException: Can't get otp code

**Comment by CWfFO** [comment]
It seems to work now :)
Next time i just follow your infos flobz. Sorry.
I did a fresh install of the opel app on a second phone. He asked to reset my PIN. I did this and now it seems to work. I keep a eye on it.
Do you have any idea why this happend?

**Comment by flobz** [comment]
Yes it happens after 20 sms received.
