### ISSUE TITLE
psa/RemoteServices/events/MPHRTServices/<VIN> does not get any MQTT data anymore

### ISSUE THREAD

**Issue by sircuri** [flobz/psa_car_controller#665]
It might not be a bug and related to PSA, but since some time I noticed that the application does not receive events anymore on the MQTT event topic 'psa/RemoteServices/events/MPHRTServices/VRXXXXXXXXXX'
I was wondering if more people observe this behavior or that it might be related to my car. I did get a software update a couple of weeks ago that was part of a large recall operation. I didn't pay attention to the data being received from MQTT at that time, so I'm not sure if it is related at all.

**Comment by papageigit** [comment]
There used to be a MQTT response in the log but I don't see it anymore, only that the connection was refused. Coincidentally, I have noticed that PSACC does not automatically refresh during charging sessions like it used to do perfectly well couple days ago. I have to go to the Peugeot app and manually refresh from there in order to get up-to-date information in PSACC/HA and the app.

**Comment by Mikado8231** [comment]
Have you data updated in the Peugeot App ? (batterie level)

Last week, I had this kind of problem, no data from psa_car_controller and Peugeot App.

I found a solution on a forum and it worked for me: _**unplug the 12v battery during 10 min**_
After plugging it back in, the car started communicating again
