### ISSUE TITLE
Urgent help - please!

### ISSUE THREAD

**Issue by wifispray** [flobz/psa_car_controller#714]
Hi All

thanks for reading. My car has been stolen, worse scenario. But I can see in my paw dashboard that the last trip was 1km. But the info doesn’t show in the map or can I find any GpS… is there anything I can find from my PSA TO HA integration. Time is of the essence on this one. 

Please can someone help

**Comment by wifispray** [comment]
@flobz if you get this.

**Comment by sod75** [comment]
I have the standalone docker install, not via addon, but it should be similar.

you can put this in your browser window
`http://192.168.0.91:5000/get_vehicleinfo/YOURVIN` 
obviously with the right IP and VIN and the gps position would be listed  in there like below

```
last_position	
  type	"Feature"
  geometry	
    coordinates	
     0	5.3326
     1	43.75192
     2	104
     type	"Point"
```

**Comment by wifispray** [comment]
Amazing. Should this work via the casa login? Currently out with no local access? It’s https not http

**Comment by wifispray** [comment]
I cant seem to access via the HA IP address with get_vehicleinfo + VIN... is there another way?

**Comment by wifispray** [comment]
Even if its via the PSA API. Sorry to keep asking, just time is key.

**Comment by flobz** [comment]
@wifispray contact Peugeot they might help you.

**Comment by wifispray** [comment]
No luck this time of year. You guys were my last hope. Thanks for replying.

**Comment by wifispray** [comment]
Also it’s a Corsa E

**Comment by larskarla** [comment]
I think it is depending on trim level of the car. 
get_vehicleinfo gives me {"coordinates": [null, null, null] because my car (Corsa-e) does not have GPS.
The only thing you can do is to start preconditioning until the battery drops down to 50%...

**Comment by wifispray** [comment]
Mine is also a Corsa E. assume it’s the same for all

**Comment by nosuchuser** [comment]
> Hi All
> 
> thanks for reading. My car has been stolen, worse scenario. But I can see in my paw dashboard that the last trip was 1km. But the info doesn’t show in the map or can I find any GpS… is there anything I can find from my PSA TO HA integration. Time is of the essence on this one.
> 
> Please can someone help

Some time has passed since the first post and I noticed you haven’t figured out a way to get this working.

My eC4 wouldn’t show gps coordinates on the app. I thought it was some kind of error on it (sorry @flobz) but upon careful inspection of the payloads I understood Stellantis was just not providing it. The latitude and longitude were empty, as a lot of other fields. 

I found it odd but at some point a friend of mine who bought another eC4 with a higher trim level got an email from Stellantis saying they were upgrading his remote services to provide vehicle position over the API. At this point I gave up and understood this was a limitation imposed by Stellantis for the current api level used by this project, as other apps I was using at the time provided location. 

Fast forward to a few months later, at which point I start seeing altitude entries on the trips list out of nowhere. Needless to say, the map page was now being wonderfully rendered with my car trips on it.

The only thing I did different was that I installed eevee (as they started providing support for our platform) and allowed them access to the Stellantis platform. 

(In the meantime I’ve seen some comments here on GitHub mentioning the API has some B2C and B2B levels and that may be it, I’m not into the subject and if there is any confirmation on this I would appreciate the added knowledge)

It may be worth the shot and trying it. The process can be done in five minutes. Then it’s a matter of looking at the car info structure to see if it returns location data. 

https://eeveeapp.com


![IMG_2098](https://github.com/flobz/psa_car_controller/assets/1007018/f64d6c41-2d81-4150-8149-81191d227f53)
![IMG_2099](https://github.com/flobz/psa_car_controller/assets/1007018/d35fb278-a418-45d0-b783-154bde432c0c)

**Comment by wifispray** [comment]
Thanks for your email

Would love to give this a try. Did you follow any kind of guide to setup?

**Comment by larskarla** [comment]
It worked! Downloaded eevee app to android phone, signed up an added the car with stellantis password. Added a home location, and today eevee app tells me "charging, location home"
get_vehicleinfo/  has gps location now!
Also, PSA car controller has altitude diff for the first time after more than 600 trips, and the map is getting data.
Corsa-e, lowest trim level, phone not connected to car with cable during the two trips tested.

**Comment by wifispray** [comment]
I get a 400 error when I try to connect EEVEE app to the Vaxhqul account.
Did I do something wrong?

**Comment by tomechio** [comment]
I'm also happy to confirm that the Eeveeapp trick worked! Yesterday I installed the app and today for the first time in 17 months I'm able to see trips on the map. Also some other data has changed from null to real figures like for example: Speed, Direction, Signal quality etc.

Thanx @nosuchuser for a great tip!

**Comment by sod75** [comment]
just to add on this.

My location worked before. Though my trips showed on the map to be flying from start to end in a direct line. Out of curiosity I also registered in the eevee app and now my position gets updated more regularly showing close to actual routes taken.

**Comment by youradds** [comment]
> I get a 400 error when I try to connect EEVEE app to the Vaxhqul account. Did I do something wrong?

I get that as well  :( I know the credentials are correct, as I use them to log in on this script (and have it saved in a password manager)

**Comment by gernot-h** [comment]
> Fast forward to a few months later, at which point I start seeing altitude entries on the trips list out of nowhere. Needless to say, the map page was now being wonderfully rendered with my car trips on it.
> 
> The only thing I did different was that I installed eevee (as they started providing support for our platform) and allowed them access to the Stellantis platform.

As this post is referenced a lot, just wanted to mention that I went through the same issues (geo coordinates and SoH not provided by Stellantis servers in the beginning), but decided not to give another party access to my data. Instead, it fixed itself a few days later out of nowhere (in case of SoH, it even took a week or so before the first data points appeared...). So perhaps, just waiting a few days might also help. :-)

**Comment by JbbDE** [comment]
what do you guys recommend for an petrol car? Am I able to add it to Eevee or is there another way to get full position information?

**Comment by GeyerA** [comment]
I can confirm that this solves the issue on missing trips im maps. Just install EEVEE and added car and trips in maps are now shown.

**Comment by noopectro** [comment]
This also appears to work on similar apps - I was having an issue getting my Vauxhall to work with the Eevee app (getting a 400 error as above).  

Instead I registered my car on the Tronity (tronity.io) app and the location started working a couple of hours later.
