### ISSUE TITLE
Psacc extremely sluggish to update values (May be the issue with the servers ?? )

### ISSUE THREAD

**Issue by vineethktpla** [flobz/psa_car_controller#862]
Psa car controller is extremely sluggish to update sensor values like battery, iginition status etc. It was not the case before, but now the battery level is updated all at once instead of sequentially ( for example, in a trip where you finish the trip and the battery level updates directly to 56% from 60% instead of 59,58,57.. ). 
Other sensors like iginition status, temperature, kinetic, takes a while to update from sleep.

For another example, iginition status moves to StartUp from stop, around 3-5 minutes after starting the trip. This makes delay and incorrect values in my HA automations. It was not the case before and was updating almost instantly.

This issue can be tied up with the rate-limit / cannot refresh remote token issue we are facing currently as both issues started almost at the same time.

PSA changed something big in their backend servers I believe. What are your thoughts ?

**Comment by kosi2801** [comment]
I have observed similar behavior regarding battery level and updates. My guess is also that PSA is currently changing their backend setup and handling of incoming API requests. I have also observed that the official Opel app changes its behavior every few days at the moment, works/fails/requests Pin etc.
At the moment actions like setting an A/C or charging schedule triggers an update, similar at start&end of a trip or when opening/closing the car. "Passive" API calls like getting battery level or waking up the car have no effect, block, or get an error (like #851).

Since the behavior currently changes on a daily basis it's not easy to implement a workaround/change at the moment I guess.
Also it's probably unknown what caused those changes on PSA side and if there is an active intent to cut down API usage from outside their own applications or if they are just rearranging their server structure.

**Comment by vineethktpla** [comment]
I found this issue is because my scanning interval for my sensor was too high. I reduced it and now fixes the problem :-)

**Comment by GeraldPape** [comment]
Maybe you tell the value that worked for you. In case someone else stumbles across this issue.

**Comment by vineethktpla** [comment]
> Maybe you tell the value that worked for you. In case someone else stumbles across this issue.

 scan_interval: 60 made the difference

- resource: "http://0.0.0.0:5000/get_vehicleinfo/VR3xxxxxxxxxxxx"
    scan_interval: 60
    sensor:
      - name: e2008
        unique_id: e2008_vehicle_info
        value_template: 'OK'
        json_attributes:
          - energy
          - timed_odometer
          - battery
          - environment
          - ignition
          - kinetic
          - last_position
          - preconditionning

**Comment by Easyrunner** [comment]
OK, where and how to set the scan interval?
